version: "3.7"
services:

  dns-server:
    image: pihole/pihole
    restart: unless-stopped
    # volumes:
      # - $PWD/custom_hosts:/etc/pihole/custom.list:rw                                    # use this for persistent custom hosts
      # - /home/dietpi/git/device-configs/config/dns/gravity.db:/etc/pihole/gravity.db:rw # use this for persistent adlists 
    ports:
      - 54:80/tcp
      - 53:53/udp
      - 53:53/tcp
    environment:
      - DNSMASQ_LISTENING=all  # required due to our internal subnet. remove this if you only intend to use cloudhole from within the subnet
      - PIHOLE_DNS_=172.16.1.5#5054
      # - WEBPASSWORD=pihole   # change this or the password will be generated automatically
    extra_hosts:
      cloudflared: 172.16.1.5 # optional - adds a readable hostname for the upstream resolver in the pi-hole web UI
      # extra.host.domain.one: 192.168.1.2
      # ...
    networks:
      default:
        ipv4_address: 172.16.1.4

  doh-proxy:
    image: visibilityspots/cloudflared
    restart: unless-stopped
    # environment: # if you want to change from the default cloudflare
    #  - UPSTREAM1=https://8.8.8.8/dns-query # Google DoH
    #  - UPSTREAM2=https://9.9.9.9/dns-query # Quad9 DoH
    networks:
      default:
        ipv4_address: 172.16.1.5

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/29 # i think this is the smallest we can go
